// Mocks generated by Mockito 5.4.6 from annotations
// in reown_core/test/shared/shared_test_utils.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i26;
import 'dart:typed_data' as _i24;

import 'package:event/event.dart' as _i8;
import 'package:http/http.dart' as _i9;
import 'package:logger/logger.dart' as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i25;
import 'package:reown_core/connectivity/i_connectivity.dart' as _i18;
import 'package:reown_core/core_impl.dart' as _i31;
import 'package:reown_core/crypto/crypto.dart' as _i27;
import 'package:reown_core/crypto/crypto_models.dart' as _i2;
import 'package:reown_core/crypto/crypto_utils.dart' as _i23;
import 'package:reown_core/crypto/i_crypto.dart' as _i10;
import 'package:reown_core/crypto/i_crypto_utils.dart' as _i5;
import 'package:reown_core/echo/i_echo.dart' as _i14;
import 'package:reown_core/events/i_events.dart' as _i15;
import 'package:reown_core/heartbit/i_heartbeat.dart' as _i16;
import 'package:reown_core/i_core_impl.dart' as _i3;
import 'package:reown_core/models/basic_models.dart' as _i36;
import 'package:reown_core/pairing/i_expirer.dart' as _i12;
import 'package:reown_core/pairing/i_pairing.dart' as _i13;
import 'package:reown_core/relay_auth/i_relay_auth.dart' as _i6;
import 'package:reown_core/relay_client/i_message_tracker.dart' as _i21;
import 'package:reown_core/relay_client/i_relay_client.dart' as _i11;
import 'package:reown_core/relay_client/json_rpc_2/src/peer.dart' as _i35;
import 'package:reown_core/relay_client/message_tracker.dart' as _i28;
import 'package:reown_core/relay_client/relay_client.dart' as _i33;
import 'package:reown_core/relay_client/relay_client_models.dart' as _i34;
import 'package:reown_core/relay_client/websocket/http_client.dart' as _i30;
import 'package:reown_core/relay_client/websocket/i_websocket_handler.dart'
    as _i22;
import 'package:reown_core/relay_client/websocket/websocket_handler.dart'
    as _i32;
import 'package:reown_core/store/i_generic_store.dart' as _i4;
import 'package:reown_core/store/i_store.dart' as _i7;
import 'package:reown_core/store/link_mode_store.dart' as _i19;
import 'package:reown_core/store/store_models.dart' as _i29;
import 'package:reown_core/verify/i_verify.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCryptoKeyPair_0 extends _i1.SmartFake implements _i2.CryptoKeyPair {
  _FakeCryptoKeyPair_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncodingParams_1 extends _i1.SmartFake
    implements _i2.EncodingParams {
  _FakeEncodingParams_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEncodingValidation_2 extends _i1.SmartFake
    implements _i2.EncodingValidation {
  _FakeEncodingValidation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIReownCore_3 extends _i1.SmartFake implements _i3.IReownCore {
  _FakeIReownCore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIGenericStore_4<T> extends _i1.SmartFake
    implements _i4.IGenericStore<T> {
  _FakeIGenericStore_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeICryptoUtils_5 extends _i1.SmartFake implements _i5.ICryptoUtils {
  _FakeICryptoUtils_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIRelayAuth_6 extends _i1.SmartFake implements _i6.IRelayAuth {
  _FakeIRelayAuth_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIStore_7<T> extends _i1.SmartFake implements _i7.IStore<T> {
  _FakeIStore_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEvent_8<T extends _i8.EventArgs> extends _i1.SmartFake
    implements _i8.Event<T> {
  _FakeEvent_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_9 extends _i1.SmartFake implements _i9.Response {
  _FakeResponse_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeICrypto_10 extends _i1.SmartFake implements _i10.ICrypto {
  _FakeICrypto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIRelayClient_11 extends _i1.SmartFake implements _i11.IRelayClient {
  _FakeIRelayClient_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIExpirer_12 extends _i1.SmartFake implements _i12.IExpirer {
  _FakeIExpirer_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIPairing_13 extends _i1.SmartFake implements _i13.IPairing {
  _FakeIPairing_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEcho_14 extends _i1.SmartFake implements _i14.IEcho {
  _FakeIEcho_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIEvents_15 extends _i1.SmartFake implements _i15.IEvents {
  _FakeIEvents_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIHeartBeat_16 extends _i1.SmartFake implements _i16.IHeartBeat {
  _FakeIHeartBeat_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIVerify_17 extends _i1.SmartFake implements _i17.IVerify {
  _FakeIVerify_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIConnectivity_18 extends _i1.SmartFake
    implements _i18.IConnectivity {
  _FakeIConnectivity_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeILinkModeStore_19 extends _i1.SmartFake
    implements _i19.ILinkModeStore {
  _FakeILinkModeStore_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogger_20 extends _i1.SmartFake implements _i20.Logger {
  _FakeLogger_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIMessageTracker_21 extends _i1.SmartFake
    implements _i21.IMessageTracker {
  _FakeIMessageTracker_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIWebSocketHandler_22 extends _i1.SmartFake
    implements _i22.IWebSocketHandler {
  _FakeIWebSocketHandler_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CryptoUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoUtils extends _i1.Mock implements _i23.CryptoUtils {
  MockCryptoUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CryptoKeyPair generateKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateKeyPair, []),
            returnValue: _FakeCryptoKeyPair_0(
              this,
              Invocation.method(#generateKeyPair, []),
            ),
          )
          as _i2.CryptoKeyPair);

  @override
  _i24.Uint8List randomBytes(int? length) =>
      (super.noSuchMethod(
            Invocation.method(#randomBytes, [length]),
            returnValue: _i24.Uint8List(0),
          )
          as _i24.Uint8List);

  @override
  String generateRandomBytes32() =>
      (super.noSuchMethod(
            Invocation.method(#generateRandomBytes32, []),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#generateRandomBytes32, []),
            ),
          )
          as String);

  @override
  _i26.Future<String> deriveSymKey(String? privKeyA, String? pubKeyB) =>
      (super.noSuchMethod(
            Invocation.method(#deriveSymKey, [privKeyA, pubKeyB]),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#deriveSymKey, [privKeyA, pubKeyB]),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  String hashKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hashKey, [key]),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#hashKey, [key]),
            ),
          )
          as String);

  @override
  String hashMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#hashMessage, [message]),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#hashMessage, [message]),
            ),
          )
          as String);

  @override
  _i26.Future<String> encrypt(
    String? message,
    String? symKey, {
    int? type,
    String? iv,
    String? senderPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #encrypt,
              [message, symKey],
              {#type: type, #iv: iv, #senderPublicKey: senderPublicKey},
            ),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(
                  #encrypt,
                  [message, symKey],
                  {#type: type, #iv: iv, #senderPublicKey: senderPublicKey},
                ),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<String> decrypt(String? symKey, String? encoded) =>
      (super.noSuchMethod(
            Invocation.method(#decrypt, [symKey, encoded]),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#decrypt, [symKey, encoded]),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  String serialize(
    int? type,
    _i24.Uint8List? sealed,
    _i24.Uint8List? iv, {
    _i24.Uint8List? senderPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #serialize,
              [type, sealed, iv],
              {#senderPublicKey: senderPublicKey},
            ),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(
                #serialize,
                [type, sealed, iv],
                {#senderPublicKey: senderPublicKey},
              ),
            ),
          )
          as String);

  @override
  _i2.EncodingParams deserialize(String? encoded) =>
      (super.noSuchMethod(
            Invocation.method(#deserialize, [encoded]),
            returnValue: _FakeEncodingParams_1(
              this,
              Invocation.method(#deserialize, [encoded]),
            ),
          )
          as _i2.EncodingParams);

  @override
  _i2.EncodingValidation validateDecoding(
    String? encoded, {
    String? receiverPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #validateDecoding,
              [encoded],
              {#receiverPublicKey: receiverPublicKey},
            ),
            returnValue: _FakeEncodingValidation_2(
              this,
              Invocation.method(
                #validateDecoding,
                [encoded],
                {#receiverPublicKey: receiverPublicKey},
              ),
            ),
          )
          as _i2.EncodingValidation);

  @override
  _i2.EncodingValidation validateEncoding({
    int? type,
    String? senderPublicKey,
    String? receiverPublicKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateEncoding, [], {
              #type: type,
              #senderPublicKey: senderPublicKey,
              #receiverPublicKey: receiverPublicKey,
            }),
            returnValue: _FakeEncodingValidation_2(
              this,
              Invocation.method(#validateEncoding, [], {
                #type: type,
                #senderPublicKey: senderPublicKey,
                #receiverPublicKey: receiverPublicKey,
              }),
            ),
          )
          as _i2.EncodingValidation);

  @override
  bool isTypeOneEnvelope(_i2.EncodingValidation? result) =>
      (super.noSuchMethod(
            Invocation.method(#isTypeOneEnvelope, [result]),
            returnValue: false,
          )
          as bool);

  @override
  bool isTypeTwoEnvelope(_i2.EncodingValidation? result) =>
      (super.noSuchMethod(
            Invocation.method(#isTypeTwoEnvelope, [result]),
            returnValue: false,
          )
          as bool);

  @override
  _i24.Uint8List encodeTypeByte(int? type) =>
      (super.noSuchMethod(
            Invocation.method(#encodeTypeByte, [type]),
            returnValue: _i24.Uint8List(0),
          )
          as _i24.Uint8List);

  @override
  int decodeTypeByte(_i24.Uint8List? byte) =>
      (super.noSuchMethod(
            Invocation.method(#decodeTypeByte, [byte]),
            returnValue: 0,
          )
          as int);

  @override
  String encodeTypeTwoEnvelope({required String? message}) =>
      (super.noSuchMethod(
            Invocation.method(#encodeTypeTwoEnvelope, [], {#message: message}),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#encodeTypeTwoEnvelope, [], {
                #message: message,
              }),
            ),
          )
          as String);

  @override
  String decodeTypeTwoEnvelope({required String? message}) =>
      (super.noSuchMethod(
            Invocation.method(#decodeTypeTwoEnvelope, [], {#message: message}),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#decodeTypeTwoEnvelope, [], {
                #message: message,
              }),
            ),
          )
          as String);
}

/// A class which mocks [Crypto].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrypto extends _i1.Mock implements _i27.Crypto {
  MockCrypto() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i3.IReownCore get core =>
      (super.noSuchMethod(
            Invocation.getter(#core),
            returnValue: _FakeIReownCore_3(this, Invocation.getter(#core)),
          )
          as _i3.IReownCore);

  @override
  _i4.IGenericStore<String> get keyChain =>
      (super.noSuchMethod(
            Invocation.getter(#keyChain),
            returnValue: _FakeIGenericStore_4<String>(
              this,
              Invocation.getter(#keyChain),
            ),
          )
          as _i4.IGenericStore<String>);

  @override
  _i5.ICryptoUtils get utils =>
      (super.noSuchMethod(
            Invocation.getter(#utils),
            returnValue: _FakeICryptoUtils_5(this, Invocation.getter(#utils)),
          )
          as _i5.ICryptoUtils);

  @override
  _i6.IRelayAuth get relayAuth =>
      (super.noSuchMethod(
            Invocation.getter(#relayAuth),
            returnValue: _FakeIRelayAuth_6(this, Invocation.getter(#relayAuth)),
          )
          as _i6.IRelayAuth);

  @override
  set keyChain(_i4.IGenericStore<String>? value) => super.noSuchMethod(
    Invocation.setter(#keyChain, value),
    returnValueForMissingStub: null,
  );

  @override
  set utils(_i5.ICryptoUtils? value) => super.noSuchMethod(
    Invocation.setter(#utils, value),
    returnValueForMissingStub: null,
  );

  @override
  set relayAuth(_i6.IRelayAuth? value) => super.noSuchMethod(
    Invocation.setter(#relayAuth, value),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  bool hasKeys(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#hasKeys, [tag]),
            returnValue: false,
          )
          as bool);

  @override
  _i26.Future<String> getClientId() =>
      (super.noSuchMethod(
            Invocation.method(#getClientId, []),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#getClientId, []),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<String> generateKeyPair() =>
      (super.noSuchMethod(
            Invocation.method(#generateKeyPair, []),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#generateKeyPair, []),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<String> generateSharedKey(
    String? selfPublicKey,
    String? peerPublicKey, {
    String? overrideTopic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateSharedKey,
              [selfPublicKey, peerPublicKey],
              {#overrideTopic: overrideTopic},
            ),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(
                  #generateSharedKey,
                  [selfPublicKey, peerPublicKey],
                  {#overrideTopic: overrideTopic},
                ),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<String> setSymKey(String? symKey, {String? overrideTopic}) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSymKey,
              [symKey],
              {#overrideTopic: overrideTopic},
            ),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(
                  #setSymKey,
                  [symKey],
                  {#overrideTopic: overrideTopic},
                ),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<void> deleteKeyPair(String? publicKey) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKeyPair, [publicKey]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> deleteSymKey(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSymKey, [topic]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String?> encode(
    String? topic,
    Map<String, dynamic>? payload, {
    _i2.EncodeOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#encode, [topic, payload], {#options: options}),
            returnValue: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<String?> decode(
    String? topic,
    String? encoded, {
    _i2.DecodeOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decode, [topic, encoded], {#options: options}),
            returnValue: _i26.Future<String?>.value(),
          )
          as _i26.Future<String?>);

  @override
  _i26.Future<String> signJWT(String? aud) =>
      (super.noSuchMethod(
            Invocation.method(#signJWT, [aud]),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(this, Invocation.method(#signJWT, [aud])),
            ),
          )
          as _i26.Future<String>);

  @override
  int getPayloadType(String? encoded) =>
      (super.noSuchMethod(
            Invocation.method(#getPayloadType, [encoded]),
            returnValue: 0,
          )
          as int);

  @override
  String? getPayloadSenderPublicKey(String? encoded) =>
      (super.noSuchMethod(
            Invocation.method(#getPayloadSenderPublicKey, [encoded]),
          )
          as String?);

  @override
  _i5.ICryptoUtils getUtils() =>
      (super.noSuchMethod(
            Invocation.method(#getUtils, []),
            returnValue: _FakeICryptoUtils_5(
              this,
              Invocation.method(#getUtils, []),
            ),
          )
          as _i5.ICryptoUtils);
}

/// A class which mocks [MessageTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageTracker extends _i1.Mock implements _i28.MessageTracker {
  MockMessageTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get context =>
      (super.noSuchMethod(
            Invocation.getter(#context),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#context),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get storageKey =>
      (super.noSuchMethod(
            Invocation.getter(#storageKey),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#storageKey),
            ),
          )
          as String);

  @override
  _i7.IStore<dynamic> get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeIStore_7<dynamic>(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i7.IStore<dynamic>);

  @override
  _i8.Event<_i29.StoreCreateEvent<Map<String, String>>> get onCreate =>
      (super.noSuchMethod(
            Invocation.getter(#onCreate),
            returnValue:
                _FakeEvent_8<_i29.StoreCreateEvent<Map<String, String>>>(
                  this,
                  Invocation.getter(#onCreate),
                ),
          )
          as _i8.Event<_i29.StoreCreateEvent<Map<String, String>>>);

  @override
  _i8.Event<_i29.StoreUpdateEvent<Map<String, String>>> get onUpdate =>
      (super.noSuchMethod(
            Invocation.getter(#onUpdate),
            returnValue:
                _FakeEvent_8<_i29.StoreUpdateEvent<Map<String, String>>>(
                  this,
                  Invocation.getter(#onUpdate),
                ),
          )
          as _i8.Event<_i29.StoreUpdateEvent<Map<String, String>>>);

  @override
  _i8.Event<_i29.StoreDeleteEvent<Map<String, String>>> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue:
                _FakeEvent_8<_i29.StoreDeleteEvent<Map<String, String>>>(
                  this,
                  Invocation.getter(#onDelete),
                ),
          )
          as _i8.Event<_i29.StoreDeleteEvent<Map<String, String>>>);

  @override
  _i8.Event<_i29.StoreErrorEvent<Map<String, String>>> get onError =>
      (super.noSuchMethod(
            Invocation.getter(#onError),
            returnValue:
                _FakeEvent_8<_i29.StoreErrorEvent<Map<String, String>>>(
                  this,
                  Invocation.getter(#onError),
                ),
          )
          as _i8.Event<_i29.StoreErrorEvent<Map<String, String>>>);

  @override
  _i8.Event<_i29.StoreSyncEvent> get onSync =>
      (super.noSuchMethod(
            Invocation.getter(#onSync),
            returnValue: _FakeEvent_8<_i29.StoreSyncEvent>(
              this,
              Invocation.getter(#onSync),
            ),
          )
          as _i8.Event<_i29.StoreSyncEvent>);

  @override
  Map<String, Map<String, String>> get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: <String, Map<String, String>>{},
          )
          as Map<String, Map<String, String>>);

  @override
  Map<String, String> Function(dynamic) get fromJson =>
      (super.noSuchMethod(
            Invocation.getter(#fromJson),
            returnValue: (dynamic __p0) => <String, String>{},
          )
          as Map<String, String> Function(dynamic));

  @override
  set data(Map<String, Map<String, String>>? value) => super.noSuchMethod(
    Invocation.setter(#data, value),
    returnValueForMissingStub: null,
  );

  @override
  String hashMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#hashMessage, [message]),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.method(#hashMessage, [message]),
            ),
          )
          as String);

  @override
  _i26.Future<void> recordMessageEvent(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#recordMessageEvent, [topic, message]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  bool messageIsRecorded(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#messageIsRecorded, [topic, message]),
            returnValue: false,
          )
          as bool);

  @override
  _i26.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  bool has(String? key) =>
      (super.noSuchMethod(Invocation.method(#has, [key]), returnValue: false)
          as bool);

  @override
  Map<String, String>? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key]))
          as Map<String, String>?);

  @override
  List<Map<String, String>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <Map<String, String>>[],
          )
          as List<Map<String, String>>);

  @override
  _i26.Future<void> set(String? key, Map<String, String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#set, [key, value]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> delete(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [key]),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> persist() =>
      (super.noSuchMethod(
            Invocation.method(#persist, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> restore() =>
      (super.noSuchMethod(
            Invocation.method(#restore, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  void checkInitialized() => super.noSuchMethod(
    Invocation.method(#checkInitialized, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HttpWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpWrapper extends _i1.Mock implements _i30.HttpWrapper {
  MockHttpWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Future<_i9.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i26.Future<_i9.Response>.value(
              _FakeResponse_9(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i26.Future<_i9.Response>);

  @override
  _i26.Future<_i9.Response> delete(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [url], {#headers: headers}),
            returnValue: _i26.Future<_i9.Response>.value(
              _FakeResponse_9(
                this,
                Invocation.method(#delete, [url], {#headers: headers}),
              ),
            ),
          )
          as _i26.Future<_i9.Response>);

  @override
  _i26.Future<_i9.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [url], {#headers: headers, #body: body}),
            returnValue: _i26.Future<_i9.Response>.value(
              _FakeResponse_9(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i26.Future<_i9.Response>);
}

/// A class which mocks [ReownCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockReownCore extends _i1.Mock implements _i31.ReownCore {
  MockReownCore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get protocol =>
      (super.noSuchMethod(
            Invocation.getter(#protocol),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#protocol),
            ),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get projectId =>
      (super.noSuchMethod(
            Invocation.getter(#projectId),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#projectId),
            ),
          )
          as String);

  @override
  String get relayUrl =>
      (super.noSuchMethod(
            Invocation.getter(#relayUrl),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#relayUrl),
            ),
          )
          as String);

  @override
  String get pushUrl =>
      (super.noSuchMethod(
            Invocation.getter(#pushUrl),
            returnValue: _i25.dummyValue<String>(
              this,
              Invocation.getter(#pushUrl),
            ),
          )
          as String);

  @override
  _i10.ICrypto get crypto =>
      (super.noSuchMethod(
            Invocation.getter(#crypto),
            returnValue: _FakeICrypto_10(this, Invocation.getter(#crypto)),
          )
          as _i10.ICrypto);

  @override
  _i11.IRelayClient get relayClient =>
      (super.noSuchMethod(
            Invocation.getter(#relayClient),
            returnValue: _FakeIRelayClient_11(
              this,
              Invocation.getter(#relayClient),
            ),
          )
          as _i11.IRelayClient);

  @override
  _i12.IExpirer get expirer =>
      (super.noSuchMethod(
            Invocation.getter(#expirer),
            returnValue: _FakeIExpirer_12(this, Invocation.getter(#expirer)),
          )
          as _i12.IExpirer);

  @override
  _i13.IPairing get pairing =>
      (super.noSuchMethod(
            Invocation.getter(#pairing),
            returnValue: _FakeIPairing_13(this, Invocation.getter(#pairing)),
          )
          as _i13.IPairing);

  @override
  _i14.IEcho get echo =>
      (super.noSuchMethod(
            Invocation.getter(#echo),
            returnValue: _FakeIEcho_14(this, Invocation.getter(#echo)),
          )
          as _i14.IEcho);

  @override
  _i15.IEvents get events =>
      (super.noSuchMethod(
            Invocation.getter(#events),
            returnValue: _FakeIEvents_15(this, Invocation.getter(#events)),
          )
          as _i15.IEvents);

  @override
  _i16.IHeartBeat get heartbeat =>
      (super.noSuchMethod(
            Invocation.getter(#heartbeat),
            returnValue: _FakeIHeartBeat_16(
              this,
              Invocation.getter(#heartbeat),
            ),
          )
          as _i16.IHeartBeat);

  @override
  _i17.IVerify get verify =>
      (super.noSuchMethod(
            Invocation.getter(#verify),
            returnValue: _FakeIVerify_17(this, Invocation.getter(#verify)),
          )
          as _i17.IVerify);

  @override
  _i18.IConnectivity get connectivity =>
      (super.noSuchMethod(
            Invocation.getter(#connectivity),
            returnValue: _FakeIConnectivity_18(
              this,
              Invocation.getter(#connectivity),
            ),
          )
          as _i18.IConnectivity);

  @override
  _i19.ILinkModeStore get linkModeStore =>
      (super.noSuchMethod(
            Invocation.getter(#linkModeStore),
            returnValue: _FakeILinkModeStore_19(
              this,
              Invocation.getter(#linkModeStore),
            ),
          )
          as _i19.ILinkModeStore);

  @override
  _i20.Logger get logger =>
      (super.noSuchMethod(
            Invocation.getter(#logger),
            returnValue: _FakeLogger_20(this, Invocation.getter(#logger)),
          )
          as _i20.Logger);

  @override
  _i7.IStore<Map<String, dynamic>> get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeIStore_7<Map<String, dynamic>>(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i7.IStore<Map<String, dynamic>>);

  @override
  _i7.IStore<Map<String, dynamic>> get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeIStore_7<Map<String, dynamic>>(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i7.IStore<Map<String, dynamic>>);

  @override
  set relayUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#relayUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set pushUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#pushUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set crypto(_i10.ICrypto? value) => super.noSuchMethod(
    Invocation.setter(#crypto, value),
    returnValueForMissingStub: null,
  );

  @override
  set relayClient(_i11.IRelayClient? value) => super.noSuchMethod(
    Invocation.setter(#relayClient, value),
    returnValueForMissingStub: null,
  );

  @override
  set expirer(_i12.IExpirer? value) => super.noSuchMethod(
    Invocation.setter(#expirer, value),
    returnValueForMissingStub: null,
  );

  @override
  set pairing(_i13.IPairing? value) => super.noSuchMethod(
    Invocation.setter(#pairing, value),
    returnValueForMissingStub: null,
  );

  @override
  set echo(_i14.IEcho? value) => super.noSuchMethod(
    Invocation.setter(#echo, value),
    returnValueForMissingStub: null,
  );

  @override
  set events(_i15.IEvents? value) => super.noSuchMethod(
    Invocation.setter(#events, value),
    returnValueForMissingStub: null,
  );

  @override
  set heartbeat(_i16.IHeartBeat? value) => super.noSuchMethod(
    Invocation.setter(#heartbeat, value),
    returnValueForMissingStub: null,
  );

  @override
  set verify(_i17.IVerify? value) => super.noSuchMethod(
    Invocation.setter(#verify, value),
    returnValueForMissingStub: null,
  );

  @override
  set connectivity(_i18.IConnectivity? value) => super.noSuchMethod(
    Invocation.setter(#connectivity, value),
    returnValueForMissingStub: null,
  );

  @override
  set linkModeStore(_i19.ILinkModeStore? value) => super.noSuchMethod(
    Invocation.setter(#linkModeStore, value),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i7.IStore<Map<String, dynamic>>? value) => super.noSuchMethod(
    Invocation.setter(#storage, value),
    returnValueForMissingStub: null,
  );

  @override
  set secureStorage(_i7.IStore<Map<String, dynamic>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorage, value),
        returnValueForMissingStub: null,
      );

  @override
  void addLogListener(dynamic Function(String)? callback) => super.noSuchMethod(
    Invocation.method(#addLogListener, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  bool removeLogListener(dynamic Function(String)? callback) =>
      (super.noSuchMethod(
            Invocation.method(#removeLogListener, [callback]),
            returnValue: false,
          )
          as bool);

  @override
  _i26.Future<void> start() =>
      (super.noSuchMethod(
            Invocation.method(#start, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<bool> addLinkModeSupportedApp(String? universalLink) =>
      (super.noSuchMethod(
            Invocation.method(#addLinkModeSupportedApp, [universalLink]),
            returnValue: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);

  @override
  List<String> getLinkModeSupportedApps() =>
      (super.noSuchMethod(
            Invocation.method(#getLinkModeSupportedApps, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void confirmOnlineStateOrThrow() => super.noSuchMethod(
    Invocation.method(#confirmOnlineStateOrThrow, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebSocketHandler].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketHandler extends _i1.Mock implements _i32.WebSocketHandler {
  MockWebSocketHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i26.Future<void> setup({required String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#setup, [], {#url: url}),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);
}

/// A class which mocks [RelayClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayClient extends _i1.Mock implements _i33.RelayClient {
  MockRelayClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Event<_i8.EventArgs> get onRelayClientConnect =>
      (super.noSuchMethod(
            Invocation.getter(#onRelayClientConnect),
            returnValue: _FakeEvent_8<_i8.EventArgs>(
              this,
              Invocation.getter(#onRelayClientConnect),
            ),
          )
          as _i8.Event<_i8.EventArgs>);

  @override
  _i8.Event<_i8.EventArgs> get onRelayClientDisconnect =>
      (super.noSuchMethod(
            Invocation.getter(#onRelayClientDisconnect),
            returnValue: _FakeEvent_8<_i8.EventArgs>(
              this,
              Invocation.getter(#onRelayClientDisconnect),
            ),
          )
          as _i8.Event<_i8.EventArgs>);

  @override
  _i8.Event<_i34.ErrorEvent> get onRelayClientError =>
      (super.noSuchMethod(
            Invocation.getter(#onRelayClientError),
            returnValue: _FakeEvent_8<_i34.ErrorEvent>(
              this,
              Invocation.getter(#onRelayClientError),
            ),
          )
          as _i8.Event<_i34.ErrorEvent>);

  @override
  _i8.Event<_i34.MessageEvent> get onRelayClientMessage =>
      (super.noSuchMethod(
            Invocation.getter(#onRelayClientMessage),
            returnValue: _FakeEvent_8<_i34.MessageEvent>(
              this,
              Invocation.getter(#onRelayClientMessage),
            ),
          )
          as _i8.Event<_i34.MessageEvent>);

  @override
  _i8.Event<_i34.MessageEvent> get onLinkModeMessage =>
      (super.noSuchMethod(
            Invocation.getter(#onLinkModeMessage),
            returnValue: _FakeEvent_8<_i34.MessageEvent>(
              this,
              Invocation.getter(#onLinkModeMessage),
            ),
          )
          as _i8.Event<_i34.MessageEvent>);

  @override
  _i8.Event<_i34.SubscriptionEvent> get onSubscriptionCreated =>
      (super.noSuchMethod(
            Invocation.getter(#onSubscriptionCreated),
            returnValue: _FakeEvent_8<_i34.SubscriptionEvent>(
              this,
              Invocation.getter(#onSubscriptionCreated),
            ),
          )
          as _i8.Event<_i34.SubscriptionEvent>);

  @override
  _i8.Event<_i34.SubscriptionDeletionEvent> get onSubscriptionDeleted =>
      (super.noSuchMethod(
            Invocation.getter(#onSubscriptionDeleted),
            returnValue: _FakeEvent_8<_i34.SubscriptionDeletionEvent>(
              this,
              Invocation.getter(#onSubscriptionDeleted),
            ),
          )
          as _i8.Event<_i34.SubscriptionDeletionEvent>);

  @override
  _i8.Event<_i8.EventArgs> get onSubscriptionResubscribed =>
      (super.noSuchMethod(
            Invocation.getter(#onSubscriptionResubscribed),
            returnValue: _FakeEvent_8<_i8.EventArgs>(
              this,
              Invocation.getter(#onSubscriptionResubscribed),
            ),
          )
          as _i8.Event<_i8.EventArgs>);

  @override
  _i8.Event<_i8.EventArgs> get onSubscriptionSync =>
      (super.noSuchMethod(
            Invocation.getter(#onSubscriptionSync),
            returnValue: _FakeEvent_8<_i8.EventArgs>(
              this,
              Invocation.getter(#onSubscriptionSync),
            ),
          )
          as _i8.Event<_i8.EventArgs>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  Map<String, _i26.Future<dynamic>> get pendingSubscriptions =>
      (super.noSuchMethod(
            Invocation.getter(#pendingSubscriptions),
            returnValue: <String, _i26.Future<dynamic>>{},
          )
          as Map<String, _i26.Future<dynamic>>);

  @override
  _i21.IMessageTracker get messageTracker =>
      (super.noSuchMethod(
            Invocation.getter(#messageTracker),
            returnValue: _FakeIMessageTracker_21(
              this,
              Invocation.getter(#messageTracker),
            ),
          )
          as _i21.IMessageTracker);

  @override
  _i4.IGenericStore<String> get topicMap =>
      (super.noSuchMethod(
            Invocation.getter(#topicMap),
            returnValue: _FakeIGenericStore_4<String>(
              this,
              Invocation.getter(#topicMap),
            ),
          )
          as _i4.IGenericStore<String>);

  @override
  _i22.IWebSocketHandler get socketHandler =>
      (super.noSuchMethod(
            Invocation.getter(#socketHandler),
            returnValue: _FakeIWebSocketHandler_22(
              this,
              Invocation.getter(#socketHandler),
            ),
          )
          as _i22.IWebSocketHandler);

  @override
  _i3.IReownCore get core =>
      (super.noSuchMethod(
            Invocation.getter(#core),
            returnValue: _FakeIReownCore_3(this, Invocation.getter(#core)),
          )
          as _i3.IReownCore);

  @override
  set jsonRPC(_i35.Peer? value) => super.noSuchMethod(
    Invocation.setter(#jsonRPC, value),
    returnValueForMissingStub: null,
  );

  @override
  set pendingSubscriptions(Map<String, _i26.Future<dynamic>>? value) =>
      super.noSuchMethod(
        Invocation.setter(#pendingSubscriptions, value),
        returnValueForMissingStub: null,
      );

  @override
  set messageTracker(_i21.IMessageTracker? value) => super.noSuchMethod(
    Invocation.setter(#messageTracker, value),
    returnValueForMissingStub: null,
  );

  @override
  set topicMap(_i4.IGenericStore<String>? value) => super.noSuchMethod(
    Invocation.setter(#topicMap, value),
    returnValueForMissingStub: null,
  );

  @override
  set core(_i3.IReownCore? value) => super.noSuchMethod(
    Invocation.setter(#core, value),
    returnValueForMissingStub: null,
  );

  @override
  _i26.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> publish({
    required String? topic,
    required String? message,
    required _i36.PublishOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [], {
              #topic: topic,
              #message: message,
              #options: options,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> publishPayload({
    required Map<String, dynamic>? payload,
    required _i36.PublishOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishPayload, [], {
              #payload: payload,
              #options: options,
            }),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<String> subscribe({required _i36.SubscribeOptions? options}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {#options: options}),
            returnValue: _i26.Future<String>.value(
              _i25.dummyValue<String>(
                this,
                Invocation.method(#subscribe, [], {#options: options}),
              ),
            ),
          )
          as _i26.Future<String>);

  @override
  _i26.Future<void> unsubscribe({required String? topic}) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [], {#topic: topic}),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> connect({String? relayUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {#relayUrl: relayUrl}),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i26.Future<void>.value(),
            returnValueForMissingStub: _i26.Future<void>.value(),
          )
          as _i26.Future<void>);

  @override
  _i26.Future<bool> handleLinkModeMessage(String? topic, String? message) =>
      (super.noSuchMethod(
            Invocation.method(#handleLinkModeMessage, [topic, message]),
            returnValue: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);

  @override
  _i26.Future<bool> handlePublish(
    String? topic,
    String? message, [
    String? attestation,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#handlePublish, [topic, message, attestation]),
            returnValue: _i26.Future<bool>.value(false),
          )
          as _i26.Future<bool>);
}
