include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
  language:
    # I've disabled it so as to make the code compile without
    # strict type-checking
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
