part of 'infinite_scroll_table.dart';

// Internal enum values are self-described by the localized column names.
// ignore_for_file: public_member_api_docs
enum InfiniteScrollTableColumnType {
  address,
  amount,
  asset,
  beneficiaryAddress,
  blank,
  date,
  delegation,
  delegationReward,
  duration,
  expiration,
  expectedProducedMomentums,
  hash,
  momentumReward,
  pillarName,
  plasma,
  producerAddress,
  recipientAddress,
  receiver,
  sender,
  sentinelAddress,
  stakingDuration,
  type,
  uptime,
  weight;

  int get flex => switch (this) {
    address => 2,
    amount => 1,
    asset => 1,
    beneficiaryAddress => 3,
    blank => 1,
    date => 1,
    delegation => 1,
    delegationReward => 1,
    duration => 1,
    expiration => 1,
    expectedProducedMomentums => 1,
    hash => 2,
    momentumReward => 1,
    pillarName => 1,
    plasma => 1,
    producerAddress => 3,
    recipientAddress => 2,
    receiver => 2,
    sender => 2,
    sentinelAddress => 3,
    stakingDuration => 1,
    type => 1,
    uptime => 1,
    weight => 1,
  };

  String name({required BuildContext context}) => switch (this) {
    address => context.l10n.address,
    amount => context.l10n.amount,
    asset => context.l10n.asset,
    beneficiaryAddress => context.l10n.beneficiaryAddress,
    blank => '',
    date => context.l10n.date,
    delegation => context.l10n.delegation,
    delegationReward => context.l10n.delegationReward,
    duration => context.l10n.duration,
    expiration => context.l10n.expiration,
    expectedProducedMomentums => context.l10n.expectedProducedMomentums,
    hash => context.l10n.hash,
    momentumReward => context.l10n.momentumReward,
    pillarName => context.l10n.name,
    plasma => context.l10n.plasma,
    producerAddress => context.l10n.producerAddress,
    recipientAddress => context.l10n.recipientAddress,
    receiver => context.l10n.receiver,
    sender => context.l10n.sender,
    sentinelAddress => context.l10n.sentinelAddress,
    stakingDuration => context.l10n.stakingDuration,
    type => context.l10n.type,
    uptime => context.l10n.uptime,
    weight => context.l10n.weight,
  };

  MainAxisAlignment get aligment => switch (this) {
    delegation => .center,
    expiration => .center,
    plasma => .center,
    _ => MainAxisAlignment.start,
  };
}
