// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:zenon_syrius_wallet_flutter/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(WalletNotificationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(NotificationTypeAdapter());
    registerAdapter(WalletNotificationAdapter());
  }
}
